### ISSUE TITLE
Store Name issues

### ISSUE THREAD

**Issue by Iyyappan123** [bthomas16/expo-stripe-purchase#1]
Hi, guys very useful and awesome plugin. But the store name is declared to be static. This simple mistake in the plugin.

**Plugin Code**
` handler.open({
                **name: 'SOTC',**
                description: '${props.description}',
                image: '${props.imageUrl}',
                amount: ${props.amount},
                currency: 'USD',
                allowRememberMe: ${props.allowRememberMe},
                email: '${props.email}',
                closed: function() {
                  window.ReactNativeWebView.postMessage("WINDOW_CLOSED");
                }
            });`
            
**Modify Code**

`handler.open({
                name: '${props.storeName}',
                description: '${props.description}',
                image: '${props.imageUrl}',
                amount: ${props.amount},
                currency: 'USD',
                allowRememberMe: ${props.allowRememberMe},
                email: '${props.email}',
                closed: function(error) {
                  window.ReactNativeWebView.postMessage("WINDOW_CLOSED");
                }
            });`
            
 Please change the mistake. I will be waiting for your response. Thank you.

**Comment by brentthomascodes** [comment]
What a silly mistake! Thank you for pointing this out. The package has been updated and released under version 1.2.4

**Comment by Iyyappan123** [comment]
@bthomas16 **Thank you** for your quick changes. I do not expect the changes. Thank you a lot and **Congratulations** on your plugin.
